### PR TITLE
Removed CalibDB

### PR DESCRIPTION
**Pull request by mdurrani808**
image

Not sure how to make this go full width

### CODE REVIEW

**Comment by crschardt** [comment]
Should this PR also include edits to https://docs.photonvision.org/en/latest/docs/calibration/calibration.html to remove all references to CalibDB?

**Comment by Juniormunk** [comment]
I have an open pr for editing the calibration page I can just pull it.

**Comment by mdurrani808** [comment]
I can edit the calibration page as well, tommorow. Simple fix

**Comment by mcm001** [comment]
skull

**Review by mcm001 — APPROVED** [review]

**Pull request merged**
