### PR TITLE
[photon-core] [2024] Cleanup and document coordinate system conversion

### PR DESCRIPTION
**Pull request by amquake**
~~Awaiting [https://github.com/wpilibsuite/allwpilib/pull/5532](https://github.com/wpilibsuite/allwpilib/pull/5532) to be merged~~ and PV updated to wpilib 2024.

Cleans up and documents confusing coordinate system conversions from AprilTag -> OpenCV -> WPILib.

### CODE REVIEW

**Comment by mcm001** [comment]
Go ahead and bump wpilib in build.gradle here if you want

**Comment by amquake** [comment]
Is this supposed to use min area rect for the corner detection algo?

https://github.com/PhotonVision/photonvision/blob/0244febc37a989eeda553c0f40e0c524cd04a97a/photon-core/src/main/java/org/photonvision/vision/pipe/impl/CornerDetectionPipe.java#L69-L72

**Comment by mcm001** [comment]
I think so? That whole algorithm seems a bit sus to me though. I feel like we should have a better way of handling that

**Comment by mcm001** [comment]
> findBoundingBoxCorners

Yeah, it is. Just checked what it does again. It finds the 4 approx-poly-dp vertices closest to the min-area-rect corners. See `detectExtremeCornersByApproxPolyDp`

**Comment by mdurrani808** [comment]
anything this is still waiting on besides a review

**Comment by amquake** [comment]
wpilib version 2024

**Review by mcm001 — APPROVED** [review]

**Pull request merged**
