### PR TITLE
Allow arbitrary networktables address

### PR DESCRIPTION
**Pull request by fovea1959**
This change allows specification of hostnames and ip4 addresses for the team number. Helpful if you want to run photonvision on the same PC as simulated robot code; just point photonvision at "localhost", and it will connect to the simulator's network tables.

This takes care of the requested feature in #570.

### CODE REVIEW

**Comment by mcm001** [comment]
LGTM though I'd like to do some testing. Do we already have any unit tests that confirm the old settings JSON is parsed correctly? That might be good to have.

**Comment by mdurrani808** [comment]
Would need a corresponding docs PR before merge IMO.

**Comment by fovea1959** [comment]
> LGTM though I'd like to do some testing. Do we already have any unit tests that confirm the old settings JSON is parsed correctly? That might be good to have.

It does do so, but I can put a unit test together. If I do so, will the PR get approved soon, or will it still be a 2024 item? If the latter, I won't put a rush on it.

Until this PR is accepted, teams do havee a workaround: put an entry for a 127.0.0.* in the /etc/hosts ("C:\Windows\System32\drivers\etc\hosts" on Windoze) file for team 9999 and using 9999 as the team number:

`127.0.0.99 roborio-9999-FRC.lan roborio-9999-FRC.local roborio-9999-FRC.frc-field.local`

**Comment by fovea1959** [comment]
> Would need a corresponding docs PR before merge IMO.

agreed. again, willing to do, but if this is getting pushed off to 2024, I won't make it a priority.

**Comment by fovea1959** [comment]
> LGTM though I'd like to do some testing. Do we already have any unit tests that confirm the old settings JSON is parsed correctly? That might be good to have.

unit test done. commit [36a35d2](https://github.com/PhotonVision/photonvision/pull/764/commits/36a35d2346cfcd8bae6e80b915ff48686b3ad09e)

**Comment by mcm001** [comment]
Thanks! Unit test looks good to me. I know it's low risk but I'm a little hesitant to make this change mid-season, and is probably a post-champs thing? So no rush here.

**Comment by fovea1959** [comment]
> Would need a corresponding docs PR before merge IMO.

Issue: PhotonVision/photonvision-docs#271
PR: PhotonVision/photonvision-docs#272

**Review by mcm001 — APPROVED** [review]

**Comment by mcm001** [comment]
oof ouch wpiformat

**Comment by mcm001** [comment]
boop

**Comment by mcm001** [comment]
Just needs wpiformat and then we can merge

**Review by mcm001 — APPROVED** [review]

**Pull request merged**
