### PR TITLE
Fix vendordep including all wpilib libraries

### PR DESCRIPTION
**Pull request by ThadHouse**

### CODE REVIEW

**Review by gerth2 — APPROVED** [review]
🚀

**Comment by calcmogul** [comment]
Needs `./gradlew spotlessApply` run.

**Review by amquake — APPROVED** [review]
Before:

image

After:

image

**Comment by gerth2** [comment]
Those test failures are strange, all tests passed in the last release.... hmmm

**Comment by ThadHouse** [comment]
Those are caused by me too. Fixing.

**Pull request merged**
