### PR TITLE
Update Java Simulation Examples

### PR DESCRIPTION
**Pull request by amquake**
Updates java examples to use new simulation framework.

[New examples readme](https://github.com/PhotonVision/photonvision/blob/2a6fa1b6ac81f239c59d724da5339f608897c510/photonlib-java-examples/README.md)

Removes `apriltagExample` and `simposeest`, replacing them with `swervedriveposeestsim` which is:
> A minimal swerve drive example demonstrating the usage of PhotonVision for AprilTag vision estimation with a swerve drive pose estimator.
> 
> The example also has simulation support with an approximation of swerve drive dynamics.

### CODE REVIEW

**Comment by amquake** [comment]
Should the example descriptions be duplicated to their individual folders (is there a nicer way to do that?) or is it fine as is?

**Comment by mcm001** [comment]
Readme is fine as is, I think! Could you add keybindings for buttons to the readme too? so like "button A does X" or "enabling auto does Y"

**Comment by mcm001** [comment]
> Readme is fine as is, I think! Could you add keybindings for buttons to the readme too? so like "button A does X" or "enabling auto does Y"

I'm blind, those exist, just not for old existing examples. That can be addressed later

**Review by mcm001 — APPROVED** [review]

**Comment by srimanachanta** [comment]
Does this close #700? I'm assuming we no longer have a requirement for a SimPoseEstimator?

**Pull request merged**
