### PR TITLE
Mark generated files as generated in gitattributes

### PR DESCRIPTION
**Pull request by spacey-sooty**
This tells git the files are generated, mostly useful for avoiding clogging up git diffs making reviewing code easier.

### CODE REVIEW

**Comment by mcm001** [comment]
What's this do? (Just describe it in the comment body)

**Review by srimanachanta — APPROVED** [review]

**Comment by mcm001** [comment]
Those 3 files shouldn't even be committed in the first place, right?

**Comment by GrahamSH-LLK** [comment]
I’m not sure this does what you think. linguist is GitHub’s language detector, so this makes those files not factor into the GitHub language percentage. This doesn’t, however, do anything to git itself or diffing.

**Comment by spacey-sooty** [comment]
> I’m not sure this does what you think. linguist is GitHub’s language detector, so this makes those files not factor into the GitHub language percentage. This doesn’t, however, do anything to git itself or diffing.


When I said diff I meant the diffs on GitHub.

> Those 3 files shouldn't even be committed in the first place, right?

Don't think so

**Comment by mcm001** [comment]
If they are never committed then I'm inclined to decline this PR

**Comment by spacey-sooty** [comment]
> If they are never committed then I'm inclined to decline this PR

Ohh yeah I thought they were being commited right now...

**Pull request closed without merging**
