### PR TITLE
Yeet PhotonCamera from PhotonPoseEstimator

### PR DESCRIPTION
**Pull request by auscompgeek**

### CODE REVIEW

**Comment by mcm001** [comment]
This breaks teams' code so not sure it's the best idea? idk

**Comment by auscompgeek** [comment]
I'm thinking we should get this in for next year?

**Comment by auscompgeek** [comment]
This patch is now broken as the PnP changes also require the camera. Any suggestions on how to proceed?

**Comment by mcm001** [comment]
I'm not sure what the cleanest way to proceed is now that we (potentially) need 2 extra double arrays passed in.

**Comment by auscompgeek** [comment]
Superceded by #840?

**Pull request closed without merging**
