### PR TITLE
[photonlib-py] Begin implementing PhotonPoseEstimator in Python

### PR DESCRIPTION
**Pull request by EWall25**
This PR adds a basic implementation of `PhotonPoseEstimator` to photonlib-py. So far, only the `MULTI_TAG_PNP_ON_COPROCESSOR` and `LOWEST_AMBIGUITY` strategies have been added.

### CODE REVIEW

**Comment by mcm001** [comment]
Looks like it's failing lint

**Comment by EWall25** [comment]
@mcm001 It should be passing now.

**Comment by mcm001** [comment]
Awesome! Thanks for adding this. Let me know when this is ready to merge, happy to do so with it in its present state since it's obviously an upgrade over nothing. Or totally happy if you wanna wait to implement more methods I personally think that some of those other strategies aren't the most useful thing in the world?

**Comment by EWall25** [comment]
I'm ready to merge now. I'll probably add the other strategies within the next week and open another PR for them. Thanks!

**Comment by mcm001** [comment]
@gerth2 if you have time?

**Review by gerth2 — COMMENTED** [review]
Looking solid overall. Code quality looks good, I'm struggling to find any logic I take issue with. Good stuff!

@EWall25 I don't see unit tests added - what's the validation that's been done so far?

**Comment by EWall25** [comment]
@gerth2 Frankly, I have no idea how to write unit tests. So far, I've tested the LOWEST_AMBIGUITY strategy and it works reliability. I don't have a field setup where I can test multi-tag.

**Comment by gerth2** [comment]
Gotcha.

FWIW - testing in photon - https://github.com/PhotonVision/photonvision/blob/master/photon-lib/py/test/photonlibpy_test.py is the one existing test, you can copy-paste that file and replace its content. as long as the file name ends with `_test` and it has functions that start with `test_`, the infrastructure will pick it up and run things to confirm functionality as part of CI.

To specifically test the pose estimation classes, my gut instinct is to make a mock implementation of `PhotonCamera` where the testcase controls what it returns. Then pass/fail on the pose estimator whether it processes the returned poses correctly.

Lemme know thoughts - if you have time and wanna learn/investigate that's probably best. If not, lets see about timing. I may have time to put something in tomorrow.... but if it drags into next week I say ship it and we'll just add a TODO to the issue.

**Comment by EWall25** [comment]
The mock `PhotonCamera` sounds like a good way to implement the tests.

I would love to learn and do this myself, but I'm not sure how much time I'll have this week. Will let you know if I can sit down for a bit and get it done, but I definitely wouldn't count on it. Thanks!

**Comment by EWall25** [comment]
@gerth2 Is there an init or setup function that is called by default in the tests? Or would I just do setup at the top of the module?

**Comment by EWall25** [comment]
@gerth2 I'm working on tests right now... almost done.

**Comment by EWall25** [comment]
@gerth2 Unit tests are done.

Quick question: When on-coprocessor multi-tag happens, will the `PhotonPipelineResult`'s `targets` list still be populated (in addition to the `multiTagResult` info)?

**Comment by mcm001** [comment]
> When on-coprocessor multi-tag happens, will the `PhotonPipelineResult`'s `targets` list still be populated (in addition to the `multiTagResult` info)?

Sometimes. See https://docs.photonvision.org/en/latest/docs/apriltag-pipelines/multitag.html

**Review by gerth2 — APPROVED** [review]
beautiful, ship it!

**Pull request merged**
