### PR TITLE
Correct all python type hinting

### PR DESCRIPTION
**Pull request by james-ward**

### CODE REVIEW

**Comment by mcm001** [comment]
Hello! Is any of this duplicated in https://github.com/PhotonVision/photonvision/pull/1548 ?

**Comment by mcm001** [comment]
Needs rebasing, but otherwise lets do it :)

**Comment by james-ward** [comment]
Rebased and ready to go

**Review by mcm001 — APPROVED** [review]

**Comment by mcm001** [comment]
Once all type hints are fixed, we should add CI steps to check these automatically

**Pull request merged**
