### PR TITLE
[build] Update wpiformat to 2024.45

### PR DESCRIPTION
**Pull request by spacey-sooty**

### CODE REVIEW

**Comment by mcm001** [comment]
This will cause merge conflicts against existing open python mrs, but users can just run the new wpiformat against them and it should be fine, right?

**Comment by spacey-sooty** [comment]
> This will cause merge conflicts against existing open python mrs, but users can just run the new wpiformat against them and it should be fine, right?

Yeah they should just be able to keep all their changes then run wpiformat

**Review by mcm001 — APPROVED** [review]
Sorry in advance then lol

**Comment by LucienMorey** [comment]
It doesn't automatically reorder things. wpiformat fails to meet your spec @mcm001

**Comment by spacey-sooty** [comment]
> It doesn't automatically reorder things. wpiformat fails to meet your spec @mcm001

Your wpiformat version is probably old, this was a very new change

**Comment by LucienMorey** [comment]
> > It doesn't automatically reorder things. wpiformat fails to meet your spec @mcm001
> 
> Your wpiformat version is probably old, this was a very new change
```
 ~/gi/photonvision/photon-l/py  tdb/add_python_sim  python -m pip list | grep wpiformat                 ✔  pyreefscape Py
wpiformat                2024.46
```
 @spacey-sooty I don't think it is

**Comment by LucienMorey** [comment]
some issues if I pin to your version as well

**Comment by spacey-sooty** [comment]
Interesting. What operating system was this?

**Comment by LucienMorey** [comment]
Ubuntu 24.04.1. Either way, if you look at the ci on our sim pr #1532, all of the ci is changing on files we haven't even touched.

**Pull request merged**
