### PR TITLE
Store the last pose on update

### PR DESCRIPTION
**Pull request by ArchdukeTim**

### CODE REVIEW

**Comment by mcm001** [comment]
Does this behavior exist in C++ too

**Comment by ArchdukeTim** [comment]
Looks like it does. Updated cpp too

**Comment by ArchdukeTim** [comment]
I'm updating the java to not clear `lastPose`, since the description mentions the last pose calculated, so it should be assumed that if a pose isn't calculated, `lastPose` will keep its current pose until a new one is calculated

**Review by mcm001 — APPROVED** [review]
LGTM

**Comment by auscompgeek** [comment]
Does this behaviour exist in Python too?

**Comment by ArchdukeTim** [comment]
Oof yes.

**Pull request merged**
