### PR TITLE
Bump wpiformat version to match wpilib

### PR DESCRIPTION
**Pull request by mcm001**

### CODE REVIEW

**Comment by KangarooKoala** [comment]
Would https://github.com/wpilibsuite/allwpilib/pull/5376 be relevant?

**Comment by mcm001** [comment]
I think so. What exactly does that PR do?

**Comment by KangarooKoala** [comment]
If I remember right, there were changes to wpiformat to where it'll use the pip clang-format package of the right version, which I think is why they removed the clang-format install and didn't specify the version.

**Comment by mcm001** [comment]
Replaced by #858

**Pull request closed without merging**
