### PR TITLE
Only return EstimatedRobotPose when timstamp differs

### PR DESCRIPTION
**Pull request by mcm001**

### CODE REVIEW

**Comment by KangarooKoala** [comment]
First, build is failing because `ret` is an `Optional<EstimatedRobotPose>`, which does not have the `timestampSeconds` field. (Also, `lastResultTimestamp` isn't getting updated) Third, you could more cleanly express the logic using [`Optional.filter`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Optional.html#filter(java.util.function.Predicate)) and [`Optional.ifPresent`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Optional.html#ifPresent(java.util.function.Consumer)):
```java
ret = ret.filter((estimate) -> Math.abs(estimate.timestampSeconds - lastResultTimestamp) > 1e-6);
ret.ifPresent((estimate) -> {
    lastResultTimestamp = estimate.timestampSeconds;
};
return ret;
```

**Comment by mcm001** [comment]
I don't have time to pick up this PR rn, but if you have time to pull these changes into photonposeestimator itself that would be awesome!

**Comment by KangarooKoala** [comment]
I'll work on that, might take a while though.

**Comment by KangarooKoala** [comment]
Alright, Java code is up on #788.

**Comment by mcm001** [comment]
Closed in favor of #788

**Pull request closed without merging**
