### PR TITLE
Add python simulation

### PR DESCRIPTION
**Pull request by LucienMorey**
We are doing the whole native python thing. We think we are most of the way through since we can run it with our robot code in sim but no data is coming through just yet. Hopefully if anyone else has other progressive we can share.

### CODE REVIEW

**Comment by mcm001** [comment]
Yall are absolutely insane for crunching through 1500 lines of language translation, love it. I was attempting to go the robotpy bindings route to side-step needing to re-implement photon sim in Python but hit build system roadblocks. If this works this'll be pretty awesome to see upstreamed.

**Comment by LucienMorey** [comment]
@mcm001 @spacey-sooty I think you're the right ones to ping here...

Some of this can and probably should be split out if you want.

- I have extended the message generator stuff to make packing functions in python. We needed it for the sim
- [153ca26](https://github.com/PhotonVision/photonvision/pull/1532/commits/153ca269d6a809b259f2fb8ab0015430df5a05bf) Identifies an inconsistency in naming with C++ and Java the message uses a lowercase 't' when the python class and every usage of it has uppercase so we get exceptions

Do you want these things prepped and sent in outside this PR?

In other news, we are driving around in our sim with simulated vision and results returning to our code. There is still more to go, but it is very close!

**Comment by spacey-sooty** [comment]
> @mcm001 @spacey-sooty I think you're the right ones to ping here...
> 
> Some of this can and probably should be split out if you want.
> 
>     * I have extended the message generator stuff to make packing functions in python. We needed it for the sim
> 
>     * [153ca26](https://github.com/PhotonVision/photonvision/pull/1532/commits/153ca269d6a809b259f2fb8ab0015430df5a05bf) Identifies an inconsistency in naming with C++ and Java the message uses a lowercase 't' when the python class and every usage of it has uppercase so we get exceptions
> 
> 
> Do you want these things prepped and sent in outside this PR?
> 
> In other news, we are driving around in our sim with simulated vision and results returning to our code. There is still more to go, but it is very close!

Im prolly not the right person to ask but having these as seperate PRs would make this more reviewable so would probably be good.

Thanks for the incredible work, you'll have to show me at SCR

**Comment by LucienMorey** [comment]
I have rebased this to get more up-to-date ci. It will need to be rebased again after #1541 gets merged because it contains those changes at the beginning of the history right now

**Comment by LucienMorey** [comment]
Well this is as ready to go as it can be. We have ported all the things we and probably most teams will need, including the test harness.

What do you want done about the lint job? #1545 broke things and I don't know how to fix it. I have tried going to both the same and a newer version of `wpiformat`. I cant get the same diff as the CI and if I manually change and run the tool it reverts things. Given that the original PR threw no errors even though you expected them to be there, I think this whole job is now pretty likely broken.

**Comment by mcm001** [comment]
The "wpiformat" workflow uploads a patch file you can apply with `git apply`, but I've pushed formatting fixes for ya

**Comment by mcm001** [comment]
Oh or apparently I don't have permission to do that. Apply this patch file: https://github.com/PhotonVision/photonvision/actions/runs/11765371019/artifacts/2168245903

**Comment by LucienMorey** [comment]
Woot! Is anything else needed from us for the time being @mcm001?

**Review by mcm001 — APPROVED** [review]
One of these days, CI will be green and yet the code is broken. But it is not this day

**Comment by LucienMorey** [comment]
@mcm001 I know you made a release a few hours ago, but would you be willing to make another one with the sim stuff, or is there a cycle time we have to wait on? I want to make life easier for the kids on my team so they don't have to install dev builds if possible

**Comment by mcm001** [comment]
Do we publish dev builds of photonlib to pypi? If not yeah I'm open to a quirk patch. When is your need by date?

**Comment by LucienMorey** [comment]
> Do we publish dev builds of photonlib to pypi? If not yeah I'm open to a quirk patch. When is your need by date?

It seems like you make things automatically. 21 hours ago lines up with what you were doing right? it seems older than whats in the github releases somehow
image

One of our last offseason projects is setting up a camera on a turret for single camera with massive effective fov action. We are working on it sporadically now, so whenever you are ready to drop a patch it would be appreciated.

**Comment by mcm001** [comment]
Yee we have got tags automated -- looks like we don't push artifacts for every commit to main like Java and C++ though. I'll drop a tag once the dust settles a bit more.

**Pull request merged**
