### PR TITLE
Break up masssive python overload hacks

### PR DESCRIPTION
**Pull request by LucienMorey**
What it says on the tin. This is all stuff from our initial effort to port the sim things. Right now it is coupled to #1557 because this fixes things up in that. Lets merge that one before dealing with this one

### CODE REVIEW

**Comment by mcm001** [comment]
Yay merge conflicts

**Review by mcm001 — APPROVED** [review]

**Comment by LucienMorey** [comment]
@mcm001 This is ready to go when you want to send it in. That CI failure is definitely not related to Python things, right? It seems to be appearing more and more

**Comment by mcm001** [comment]
Yeah, looks to be a flake. Could you open an issue to track that?

**Comment by LucienMorey** [comment]
> Yeah, looks to be a flake. Could you open an issue to track that?

See #1574

**Pull request merged**
