### PR TITLE
Remove unused JNI artifacts

### PR DESCRIPTION
**Pull request by Gold856**
Also removes unnecessary `_M_` prefix from artifacts.

### CODE REVIEW

**Comment by mcm001** [comment]
JNI artifacts are unused since the JNI so ships with -cpp right? But lit Lgtm

**Comment by mcm001** [comment]
Would be good to quickly sanity check that all the .so's are in the right place still

**Comment by Gold856** [comment]
Archives still have the libraries and loading the JNI libraries in sim seems to work, so we should be good.

**Comment by mcm001** [comment]
Man, we really need a roborio automated test harness. Whatevs

**Review by mcm001 — APPROVED** [review]

**Pull request merged**
