### PR TITLE
bump python dependencies for 2025

### PR DESCRIPTION
**Pull request by LucienMorey**
I tasked my team with updating our upcoming Reefscape codebase to target 2025 packages, only to realise we have created an unsolvable dependency nightmare with these things being neglected...

### CODE REVIEW

**Comment by mcm001** [comment]
LOL fantastic. Do we need something like photonlib-python-examples to try actually building a robot project automatically for us?

**Review by spacey-sooty — APPROVED** [review]
If CI is green Lgtm

**Comment by mcm001** [comment]
Get wpiformatted, nerd

**Comment by LucienMorey** [comment]
> Get wpiformatted, nerd

This whole autoformatter thing being broken is making me very sad

**Comment by mcm001** [comment]
It looks like the diff it suggests is reasonable?

**Comment by LucienMorey** [comment]
> It looks like the diff it suggests is reasonable?

too much manual formatting with an automatic tool that is giving me bad outputs though

**Comment by LucienMorey** [comment]
> LOL fantastic. Do we need something like photonlib-python-examples to try actually building a robot project automatically for us?

Something like this might be good. What would you expect it to look like?

In my head we want to build based on the package published to pypi to get a full closed loop but that will have some lag on it right?

I suppose we could make proper example projects install their dependencies and then try to install this manually and see if it spits the dummy because things are unsolvable?

**Comment by mcm001** [comment]
Pip install . Within the photon lib project and in an isolated clean venv is probably sufficient for a first prototype. Or, we can look at uploading wheels as GitHub actions artifacts and having a subsequent job download and install the wheels without hitting pypi

**Comment by LucienMorey** [comment]
> Pip install . Within the photon lib project and in an isolated clean venv is probably sufficient for a first prototype. Or, we can look at uploading wheels as GitHub actions artifacts and having a subsequent job download and install the wheels without hitting pypi

Added a note in the big update issue

**Pull request merged**
