### PR TITLE
Bump wpilib version and replace VideoMode equality

### PR DESCRIPTION
**Pull request by mcm001**

### CODE REVIEW

**Comment by srimanachanta** [comment]
If it is just MacOS builds, why not hold off until the beta releases are done so more concrete stuff can be implemented? We should wait till at least https://github.com/wpilibsuite/allwpilib/pull/5397 is merged.

**Comment by srimanachanta** [comment]
I just combined the changes from #859 due to our discussion in discord regarding bumping this PR regardless

**Comment by mcm001** [comment]
Looks like this breaks on raspberry pi devices:

image
https://discord.com/channels/725836368059826228/753739620050665523/1122179346929561700

**Comment by srimanachanta** [comment]
> Looks like this breaks on raspberry pi devices:
> 
> 
> 
> image
> 
> https://discord.com/channels/725836368059826228/753739620050665523/1122179346929561700

Are you loading from a legacy confit? Try a fresh install

**Comment by srimanachanta** [comment]
Just in case I don't remember when this gets reviewed next, adding an equality check makes libcamera non functional for some reason.

**Comment by mcm001** [comment]
Unclear if this PR is still relevant?

**Comment by srimanachanta** [comment]
> Unclear if this PR is still relevant?

This PR actually breaks libcamera completely for some reason, might be better just to kill it cause the wpilib bump is already implemented

**Comment by mcm001** [comment]
Closing, can reopen later. Mac issue still is present, need a new issue cut to disable mac builds

**Pull request closed without merging**
