### PR TITLE
[photon-client] Change UI naming schema from CV to PV

### LINKED ISSUE #922: Remove ChameleonVision naming scheme
Some UI components (cv-slider for example) and core components (CVMat) are prefixed with CV (standing for chameleon vision). This distinction is no longer relevant and should either be renamed to PV(object) or the code should be removed if it is no longer used.

### PR DESCRIPTION
**Pull request by srimanachanta**
closes #922

### CODE REVIEW

**Comment by mcm001** [comment]
Why not take this chance to give things more descriptive names? Like why do we even have CvSlider? What's different about it vs v-slider?

**Comment by srimanachanta** [comment]
> Why not take this chance to give things more descriptive names? Like why do we even have CvSlider? What's different about it vs v-slider?

It's just helpful because it integrates a tooltip and a label into the input field. PV is an enough of a discriminator for each input field's unique features and styling when compared to the usual v-comp.

**Comment by mcm001** [comment]
> > Why not take this chance to give things more descriptive names? Like why do we even have CvSlider? What's different about it vs v-slider?
> 
> It's just helpful because it integrates a tooltip and a label into the input field. PV is an enough of a discriminator for each input field's unique features and styling when compared to the usual v-comp.

Yeah I guess "tooltipped-labeled-slider" is a mouthful. But in general descriptive names are good

**Comment by srimanachanta** [comment]
> > > Why not take this chance to give things more descriptive names? Like why do we even have CvSlider? What's different about it vs v-slider?
> > 
> > 
> > It's just helpful because it integrates a tooltip and a label into the input field. PV is an enough of a discriminator for each input field's unique features and styling when compared to the usual v-comp.
> 
> Yeah I guess "tooltipped-labeled-slider" is a mouthful. But in general descriptive names are good

I agree, just a mouthfull

**Review by mcm001 — APPROVED** [review]

**Pull request merged**
