### PR TITLE
Correct image capture time

### LINKED ISSUE #498: simposeest imageCaptureTime incorrect
In the Java simposeest example, the [`DrivetrainPoseEstimator`](https://github.com/PhotonVision/photonvision/blob/master/photonlib-java-examples/src/main/java/org/photonlib/examples/simposeest/robot/DrivetrainPoseEstimator.java#L89) is miscalculating `imageCaptureTime`.

```
double imageCaptureTime = Timer.getFPGATimestamp() - res.getLatencyMillis();
```

`Timer.getFPGATimesptamp()` returns the current time in seconds, but `res.getLatencyMillis()` is in miliseconds.

I believe this should be
```
double imageCaptureTime = Timer.getFPGATimestamp() - res.getLatencyMillis() / 1000; 
```

### PR DESCRIPTION
**Pull request by agasser**
`Timer.getFPGATimesptamp()` returns the current time in _seconds_, but `res.getLatencyMillis()` is in _miliseconds_.

Fixes #498

### CODE REVIEW

**Comment by shueja-personal** [comment]
How does this commit fix the issue? Don't you need to multiply one or divide the other by 1000?

**Comment by agasser** [comment]
Yikes, I don't know how I managed to get that wrong. It's fixed now.

**Review by gerth2 — COMMENTED** [review]
yup

**Comment by gerth2** [comment]
Nitpick - `d` is possibly going to cause some lack of resolution if millis ever returns a fraction. And also might be confusing to a newbie not familiar with the syntax (since that line shows up with the docs). But I don't think it's worth blocking a merge till we know there's a real issue.

**Comment by agasser** [comment]
> Nitpick - `d` is possibly going to cause some lack of resolution if millis ever returns a fraction.
Can you explain?

I'm fine just using an integer or using `1000.0` if its easier to read.

**Comment by gerth2** [comment]
`1000.0` would be my preference - simply because it still reads well, and future-proofs against keeping things floating point. Which, as far as I know, is generally "best practice" for FRC hardware and purposes.

**Review by shueja-personal — APPROVED** [review]

**Pull request merged**
