### PR TITLE
Revert to mjpeg

### PR DESCRIPTION
**Pull request by gerth2**
Update backend to fps limit the mjpeg streams
Update frontend to use mjpeg streams

### CODE REVIEW

**Comment by mdurrani808** [comment]
When you have two streams open, switch to driver mode, switch off from driver mode, the second stream doesn't show up at times. 
chunk-vendors.8dba6e5e.js:352 
        
       WebSocket connection to 'ws://localhost:5800/websocket_data' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

I also made it crash once but can't seem to do it anymore.

CS: Integrated_Webcam: Disconnected from \\?\usb#vid_0c45&pid_6723&mi_00#6&279498d4&0&0000#{e5323777-f976-4f5b-9b55-b94699c46e44}\global
[2022-12-23 11:44:51] [General - NTDataPublisher] [DEBUG] Driver mode is already true
[2022-12-23 11:44:51] [General - ConfigManager] [DEBUG] Saving to disk...
[2022-12-23 11:44:51] [General - ConfigManager] [INFO] Settings saved!
CS: Integrated_Webcam: Connecting to USB camera on \\?\usb#vid_0c45&pid_6723&mi_00#6&279498d4&0&0000#{e5323777-f976-4f5b-9b55-b94699c46e44}\global
[2022-12-23 11:44:51] [Camera - USBCameraSource - Integrated_Webcam] [DEBUG] Setting camera exposure to 100
[2022-12-23 11:44:51] [Camera - USBCameraSource - Integrated_Webcam] [DEBUG] Setting auto exposure to false
[2022-12-23 11:44:53] [General - ConfigManager] [DEBUG] Saving to disk...
[2022-12-23 11:44:53] [General - ConfigManager] [INFO] Settings saved!
[2022-12-23 11:44:56] [VisionModule - VisionModule - Integrated_Webcam] [INFO] Setting pipeline to 0
[2022-12-23 11:44:56] [VisionModule - VisionModule - Integrated_Webcam] [INFO] Pipeline name: New Pipeline
[2022-12-23 11:44:56] [VisionModule - PipelineManager] [DEBUG] Creating AprilTag pipeline
[2022-12-23 11:44:56] [VisionModule - AprilTagDetector] [DEBUG] Creating detector with params AprilTagDetectorParams{tagFamily=tag36h11, decimate=1.0, blur=0.0, threads=4, debug=false, refineEdges=false}
Created detector at idx 4
[2022-12-23 11:44:56] [VisionModule - VisionSourceSettables] [INFO] Setting video mode to FPS: 30 Width: 1280 Height: 720 Pixel Format: kMJPEG
CS: Integrated_Webcam: Disconnected from \\?\usb#vid_0c45&pid_6723&mi_00#6&279498d4&0&0000#{e5323777-f976-4f5b-9b55-b94699c46e44}\global
[2022-12-23 11:44:56] [General - NTDataPublisher] [DEBUG] Pipeline index is already 0
[2022-12-23 11:44:56] [General - NTDataPublisher] [DEBUG] Driver mode is already false
CS: Integrated_Webcam: Connecting to USB camera on \\?\usb#vid_0c45&pid_6723&mi_00#6&279498d4&0&0000#{e5323777-f976-4f5b-9b55-b94699c46e44}\global
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffe93a9122e, pid=6764, tid=7684
#
# JRE version: OpenJDK Runtime Environment AdoptOpenJDK (11.0.8+10) (build 11.0.8+10)
# Java VM: OpenJDK 64-Bit Server VM AdoptOpenJDK (11.0.8+10, mixed mode, tiered, compressed oops, g1 gc, windows-amd64)
# Problematic frame:
# C  [VCRUNTIME140.dll+0x122e]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\Owner\hs_err_pid6764.log
[thread 7524 also had an error]
[thread 5716 also had an error]
[thread 9156 also had an error]
[thread 11932 also had an error]
[thread 11060 also had an error]
[thread 4480 also had an error]

**Comment by mdurrani808** [comment]
Dashboard to cameras tab back to dashboard makes stream1 go away.

**Comment by gerth2** [comment]
'ws://localhost:5800/websocket_data` would imply the whole backend is down somehow, which would correlate to the stack trace you posted. The crash points to cscore's camera connection, not the websocket streams.

I have been able to still get the web "can't find the thing you asked for" placeholder icon by clicking back and forth fast enough. Unfortunately, it's browser side:
1) opening a second tab shows the mjpeg stream no problem
2) refreshing the broken page seems to open it just fine.

From my quick experiments, at least on chrome, it seems to be triggered when the `src` attribute of some dom element changes too rapidly. For a while we were asking the site to connect to port zero (which failed repeatedly) and then shortly after to connect to a real port. Despite the fact the port was legit and actively serving jpeg frames, chrome refused to show it (presumably gave up on the dom element?).

I can do a quick look to see if there's an easy way to rate-limit the change

**Comment by mcm001** [comment]
So much better on my Ubuntu laptop. I can try with my limelight when I get home, but lgtm. Can't reproduce any of the streaming stopped things on Chromium

**Review by mcm001 — APPROVED** [review]

**Comment by amquake** [comment]
I can replicate what @mdurrani808 sees(not super consistently), **specifically** when there is a target in view. Similar to #595, with the stream disappearing despite still seeing the target info, I can switch 2d->3d or "cameras" tab or driver mode without problem as long as there is no target. When I point the camera at a target and switch 2d->3d, most of the time the stream will hang for about a minute. The "cameras" tab or driver view will still show the raw view.

**Review by mcm001 — APPROVED** [review]

**Pull request merged**
