### PR TITLE
Enable multi-CSI-camera with libcamera

### PR DESCRIPTION
**Pull request by BytingBulldogs3539**
Adjusts JNI for multicamera changes. Also rewrites VisionSourceManager for multicamera changes and QOL changes. Also fixes issue #1028.

### CODE REVIEW

**Comment by BytingBulldogs3539** [comment]
PrevCapture
PrevCapture1
Capture

**Comment by mcm001** [comment]
Some of those other metrics look a bit sus to me -- idk about you

**Comment by SeanErn** [comment]
image
I get a 0fps metric with Apriltag mode. Weirdly, all the other pipeline types work fine...

**Comment by BytingBulldogs3539** [comment]
> Some of those other metrics look a bit sus to me -- idk about you

Other than the temp matrix everything else is fine. The RPI 5 should report 4mb for GPU memory (https://forums.raspberrypi.com/viewtopic.php?t=358327). Occasionally I get an unknown value but a refresh does fix it. Additionally, this was with 3 cameras all running non driver mode pipelines so I would expect the cpu to be pegged.

**Review by mcm001 — APPROVED** [review]
multi-cam works on pi 5 anyways, shipiiiitiiiij;dasfj;lkdfasjk;

**Pull request merged**
