### PR TITLE
Show Saved Snapshots in UI

### PR DESCRIPTION
**Pull request by srimanachanta**
Styling is still WIP but here is the logic

### CODE REVIEW

**Comment by srimanachanta** [comment]
image
image
image

This is functional and styled enough imo.

**Comment by srimanachanta** [comment]
The image viewer is fine on mobile but overall the scroll system is quite poor on mobile but there isn't much to be done for that.

**Comment by mcm001** [comment]
Should saved snapshots go under the camera control tab instead of device control? I know right now they all go into the same folder, but we can just, not do that

**Comment by srimanachanta** [comment]
> Should saved snapshots go under the camera control tab instead of device control? I know right now they all go into the same folder, but we can just, not do that. This should make it easier to in the future allow replay

If we put it under

**Review by mcm001 — APPROVED** [review]

**Pull request merged**
