### PR TITLE
[build] Update Gradle to 8.10.2

### PR DESCRIPTION
**Pull request by spacey-sooty**
Matches wpilib for 2025

### CODE REVIEW

**Review by mcm001 — APPROVED** [review]
Lgtm if ci passes

**Comment by spacey-sooty** [comment]
Blocked on removing runtime detector usage

**Comment by mcm001** [comment]
As long as this works on an orange pi, rpi, and Linux x86, I'm happy

**Comment by spacey-sooty** [comment]
We want 8.11

**Pull request closed without merging**
