### PR TITLE
Matching cameras by path ID

### PR DESCRIPTION
**Pull request by MrRedness**
Allows multiple cameras of the same model to be used while ensuring they stay tied to the physical camera and not the port. Matching occurs when first connecting cameras so swapping the ports while PV is running will swap the virtual cameras until a restart. Currently only tested on Linux.

### CODE REVIEW

**Comment by mcm001** [comment]
How much work is it to add a unit test that fails with the old system but passes now? Bonus points if we can copy paths and stuff from some physical cameras

**Comment by MrRedness** [comment]
I don't have much experience with unit tests but I can give it a shot. Doesn't sound complex

**Comment by MrRedness** [comment]
I added a couple asserts that fail on an older version
- Checks for proper suffix added to the second camera when it matches first camera's name
- Ensures each config is tested by path before defaulting to name
- Also checks that they end up matched by id rather than path if possible

**Comment by MrRedness** [comment]
Any updates on testing this?

**Comment by MrRedness** [comment]
> See "Multicam Test" [here](https://docs.google.com/document/d/1DAPOnU2NfOp91UnMQnkhyiUAanlCDJ6zl_YsCkCMZdA/edit?usp=sharing)

Cool. So the only gripes you have are with the calibration side, correct? I can probably take a look at downloading/sharing calibration data between cameras when I have some time, but I imagine that's outside the scope of this PR.

**Comment by mcm001** [comment]
I would agree, and argue the current system is working as intended. If this code works any reason not to merge now?

**Comment by amquake** [comment]
This is not my doc, its from @asid61. I think the calibration should be downloadable/uploadable as mentioned, which would be a separate pr.

**Review by mcm001 — APPROVED** [review]
We ball

**Pull request merged**
